[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
core = { path = "../core" }
analyzer = { path = "../analyzer" }
serde_json = "1.0"